services:
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    container_name: hono-auth-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=todos
